version: '3.9'

services:
  taskservice:
    image: 'ilqar/taskservice:lastest'
    ports:
      - '8080:8080'
    depends_on:
        - taskdb
    deploy:
        restart_policy:
            condition: on-failure
            delay: 30s
            max_attempts: 3
            window: 120s
    environment:
        SPRING_APPLICATION_NAME: taskservice
        SPRING_PROFILES_ACTIVE: default
        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/taskdb?useSSL=false&serverTimezone=UTC
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
    networks:
        - bridge

  taskdb:
      image: mysql:8.0
      cap_add:
        - SYS_NICE
      restart: always
      environment:
        - MYSQL_DATABASE=taskservice
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - '3307:3306'
      networks:
        - bridge

  userdb:
      image: mysql:8.0
      cap_add:
        - SYS_NICE
      restart: always
      environment:
        - MYSQL_DATABASE=userdb
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - '3308:3306'
      networks:
        - bridge

  submissondb:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=submissiondb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3309:3306'
    networks:
      - bridge

networks:
    bridge:
        driver: bridge